apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  labels:
    app: frontend-external
spec:
  selector:
    matchLabels:
      name: frontend-external
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
