apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  labels:
    name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
