name: Docker Image Build test action

on:
  push:
    branches: [ "poc" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file /src/frontend/Dockerfile --tag frontend:$(date +%s)
