name: Docker Image Build test action

on:
  push:
    branches: [ "poc" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
       uses: docker/build-push-action@v6
       with:
         context: ./src/frontend/
      -
       name: Build the Docker image
       run: docker build . --tag rontend:$(date +%s)
