name: Docker Image Build test action

on:
  push:
    branches: [ "poc" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
       uses: docker/build-push-action@v6
       with:
         context: "{{defaultContext}}:/src/frontend/"
      -
       name: publish files to artifact
       uses: actions/upload-artifact@v4
       with:
         context: "{{defaultContext}}:/src/frontend/"
         name: ${{github.run_number}}
         path: .
